### ISSUE TITLE
issue with visions application in pandas_profiling __version__ = "2.6.0" in Python 3.9.7

### ISSUE THREAD

**Issue by bi2017dg** [ydataai/pandas-profiling#1018]
### Current Behaviour

I have uninstalled visions 0.7.5 and installed 0.7.4 for pandas_profiling even then I have the same error.
 it pops  with ModuleNotFoundError: No module named 'visions.application' from jupiter run

I have-> Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
pandas_profiling =__version__ = "2.6.0"

This is very simple code below
================
import pandas as pd  # pip install pandas openpyxl
from pandas_profiling import ProfileReport  # pip install pandas-profiling

# Read CSV File
# importing the data
df=pd.read_csv(r'C:\Users\myname\Downloads\test.csv')

# Create Pandas Profiling Report
profile = ProfileReport(df, title="Pandas Profiling Report")
#profile.to_file('test.html')

### Expected Behaviour

NA

### Data Description

NA

### Code that reproduces the bug

```Python
import pandas as pd  # pip install pandas openpyxl
from pandas_profiling import ProfileReport  # pip install pandas-profiling
# Read CSV File
# importing the data
df=pd.read_csv(r'C:\Users\myname\Downloads\test.csv')

# Create Pandas Profiling Report
profile = ProfileReport(df, title="Pandas Profiling Report")
#profile.to_file('test.html')
```

### pandas-profiling version

__version__ = "2.6.0"

### Dependencies

```Text
nA
```

### OS

WINDOWS10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @bi2017dg,

this error happens because in release 2.6.0 the version for jinja2 was not pinned and we have instead `jinja2>=2.11.1`. Has Jinja is not in its version 3 and has deprecated the function `escape`, you're getting that error. 
There are 2 ways to overcome that issue:
- Installation of the last version from pandas-profiling
- After pandas-profiling 2.6.0 is installed you have to force a jinja2 installation with a compatible version - 2.11.3 will suffice. 

Let me know if this helps, I'll consider the issue closed.
