### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by marcelovalentimsilva** [ydataai/pandas-profiling#1241]
### Current Behaviour

[This is how the High correlation in the Titanic dataset from Kaggle appeared previously.docx](https://github.com/ydataai/pandas-profiling/files/10486212/This.is.how.the.High.correlation.in.the.Titanic.dataset.from.Kaggle.appeared.previously.docx)

### Expected Behaviour

The only problem is that the correlations showed the two sides, which is not a good idea. If A is correlated to B, than surely B is correlated to A and there is no need to appear.
But besides this, now, some correct correlations are not appearing anymore.  The threshold may have diminished.

### Data Description

You use Titanic Dataset from Kaggle

### pandas-profiling version

2.6.2

### Dependencies

```Text
no dependencies
```

### OS

Windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
@marcelovalentimsilva just to double check, did you mean pandas-profiling version==3.6.2 ?

The behavior you mention is intended and it was a request in order to reduce the duplication of information (warning lists were huge because of this), which as you've mentioned is surely true. 

I'll be closing this issue, but let me know if there is any other request from your side.
