### ISSUE TITLE
Pandas_Profiling install issue

### ISSUE THREAD

**Issue by ttxslxm** [ydataai/pandas-profiling#910]
can someone help me out

I tried download the packaging from github and also from Python website . after copy the whole folder into the site-packages .  when I run the code it give me error like the attached picture ,  I am sure the package I downloaded is the completed file. but the error give the =feeling still missing one part.  somethings called Visions 
<img width="722" alt="Capture" src="https://user-images.githubusercontent.com/69296564/150756246-7d8dd0b8-242e-4aa8-b57d-11de49fd4a02.PNG">

**Comment by abhicantdraw** [comment]
You don't have to copy the folder into site-packages. You shouldn't even, because when you copy just the folder, you end up leaving out all the dependencies that the package requires during installation. 

Please follow the documentation for installing the package - [](https://github.com/pandas-profiling/pandas-profiling#installation) , preferably in a virtual environment. 

It's worth looking into how to create a virtual environment using venv or Anaconda before trying out packages on your machine - [](https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/) . Once you've set this up, you can install pandas-profiling in it.

The method you've used is an incomplete way of having a package to use.

**Comment by fabclmnt** [comment]
Closing the issue based on @abhicantdraw explanation.

**Comment by ttxslxm** [comment]
I tried two ways by using PIP or Conda, but both failed that's why I tried the third way mentioned there ,
quote begin
Download the source code by cloning the repository or click on [Download ZIP](https://github.com/ydataai/pandas-profiling/archive/master.zip) to download the latest stable version.

Install it by navigating to the proper directory and running:
 quote end
