### ISSUE TITLE
TypeError: _plot_histogram() got an unexpected keyword argument 'title'

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [ydataai/pandas-profiling#950]
I got this error running on google colab
TypeError: _plot_histogram() got an unexpected keyword argument 'title'

**Comment by elbg** [comment]
This snippet reproduces the error :

```
import seaborn as sns
from pandas_profiling import ProfileReport
df = sns.load_dataset('titanic')
profile = ProfileReport(df, title="Pandas Profiling Report", explorative=True)
```

**Comment by elbg** [comment]
This snippet reproduces the error
```
    from pandas_profiling import ProfileReport
    import seaborn as sns
    df = sns.load_dataset('titanic')
    profile = ProfileReport(df, title="Pandas Profiling Report")
```

**Comment by Daniel-Trung-Nguyen** [comment]
@elbg, you can restart the runtime after installing the package on Colab and it should work

**Comment by TianruiZhang** [comment]
Here is my solution, I tried it in Google Colab and it worked!

```
!pip install numpy==1.21.4
!pip install pandas==1.3.4
!pip install pandas-profiling==3.1.0
```

**Comment by aronvandepol** [comment]
> Here is my solution, I tried it in Google Colab and it worked!
> 
> ```
> !pip install numpy==1.21.4
> !pip install pandas==1.3.4
> !pip install pandas-profiling==3.1.0
> ```

This did not solve the issue for me.

**Comment by sbrugman** [comment]
More details are needed to reproduce this issue. Please make sure you update to the latest version of pandas-profiling (as 1.4.1 is often available by default, see [this](https://pandas-profiling.ydata.ai/docs/master/rtd/pages/support.html) support page).

**Comment by aronvandepol** [comment]
@sbrugman for me - i tried several versions (including 1.4.1) and came to the conclusion that it only worked if I pass `minimal=True`.

**Comment by sbrugman** [comment]
Tested the snippet from @elbg, and this error occurs when using outdated versions of the package.

Ensure that you are using the latest version, and when in a notebook, ensure that you've restarted the kernel when needed! 
Also make sure that you install in the right environment (please use `!{sys.executable} -m pip install -U pandas-profiling`!). 
Read more [here](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/).

This issue is raised every now and then, and should be documented under [frequent issues](https://pandas-profiling.ydata.ai/docs/master/rtd/pages/support.html). (PR welcome)

@aronvandepol @Daniel-Trung-Nguyen Please let me know if the issue still persists after these steps.
